server.port: 0
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: currency-service
        uri: lb://currency-service
        predicates:
        - Path=/currency-exchange/**
      - id: country-service
        uri: lb://country-service
        predicates:
        - Path=/country-info/**
      - id: /weather-service
        uri: lb:///weather-service
        predicates:
        - Path=/weather/**
      - id: /info-service
        uri: lb:///info-service
        predicates:
        - Path=/info/**